### ISSUE TITLE
Retail Support for Enterprise

### ISSUE THREAD

**Issue by clairequigley** [Shopify/mas-intake#150]
# Content
**Due Date**
2023-08-07

**Created At**
2023-07-18

**Completed At**
No data to import.

**Last Modified**
2023-08-01

**Parent task**
No data to import.

**Status**
In Progress

**Urgency of request**
No data to import.

**Request Category**
No data to import.

**Requester Team**
No data to import.

**Section/Column**
Requests (not Code Yellow)

**Assignee**
Vanessa Robak

**Assignee Email**
vanessa.robak@shopify.com

**Tags**
mas-eom-report,mas-triage

**Notes**
Your team:
MA Solutions
Title of your request:
Retail Support for Enterprise
Urgency of request:
Timely / less than 2 weeks
Request Category:
Consultation Select from one of the below services for consultation:
Business Impact Assessment Describe the change/rollout in detail:
Currently there is no defined retail enterprise merchant offering, and enterprise level merchants are receiving inconsistent support depending on their entry point (i.e. through KA queues or through retail direct phone number). In addition, retail troubleshooting isn't necessarily aligned with Key Account merchants at scale (ie. x number of locations or card readers, etc). RTMS is not 24/7 and while we can upskill Key Account Support team for basic POS troubleshooting, bug identification and more complex technical issues might not be feasible given generalist model. Other points of concern: lack of access to retail devs; no Retail ping in #ka-innovating-support; and limited coverage, globally. What do you need from MAS?:
* Act as Retail Support Process SME in workstream space
* Establish first info gathering for project/proposal to determine impact on Retail and feasibility
* Outline MX for support flow
* Identify existing reporting * Identify ticket volume
* Provide MAS assessment of next steps for project
Relevant links to any documentation:
gDrive Folder - https://drive.google.com/drive/folders/1CNtgcqW68GjipFs7tYIS6SOj6nBZ30Ke
Project Summary - https://docs.google.com/document/d/1nfYSpgjza9tQykVxUicjtUuOjyOsOzxHQNUwCVtymeA/edit#heading=h.y97n0qaji3p8
Slack channel for conversation: https://shopify.slack.com/archives/C05H7CLQL8P
DELIVERABLES
———————————————
This task was submitted through Merchant Acceleration Solutions - Request Form
https://form.asana.com/?k=AtARQ4yV8kubgZDp8Csojg&d=14611911983641

**Estimated time**
No data to import.

**Actual time**
12:20

**Request Summary (MAS)**
No data to import.

**Battle Card Recommendation (MAS)**
No data to import.

**MAS Collabs**
Van Robak

**Requester Name**
Jess Boyer
# Task List

```[tasklist]
# Linked Issues
- [ ] https://github.com/Shopify/mas-intake/issues/94
- [ ] https://github.com/Shopify/mas-intake/issues/95
- [ ] https://github.com/Shopify/mas-intake/issues/96
- [ ] https://github.com/Shopify/mas-intake/issues/97
- [ ] https://github.com/Shopify/mas-intake/issues/98
- [ ] https://github.com/Shopify/mas-intake/issues/99
- [ ] https://github.com/Shopify/mas-intake/issues/100
```

**Comment by anabear** [comment]
@robaksacet if the issue has been closed, can the subtasks be closed also?

**Comment by robaksacet** [comment]
Not sure best practice here, open to suggestions - I will continue to work with Jess Boyer on this project as it splits into workstreams, but unsure if I should leave this task open and add tasks, or create a new "Retail x Enterprise - Phase 2  Workstreams" issue OR create a new issue for each workstream build for the project?

If we're going with option 2 or 3, then yeah all the subtasks on this one can be closed up.

**Comment by anabear** [comment]
If this stage of the project has been completed, i'd suggest to close the associated subtasks and open a new issue 'Retail x Enterprise - Phase 2 Workstreams' and create a task list on it with a new due date and details.
